### PR TITLE
Add a placeholder for Pancake game framework

### PR DESCRIPTION
**Pull request by felladrin**
I've noticed Pancake could be added to the list, as it has everything needed to create a Breakout game. So I purpose adding this placeholder as a reminder.

Maybe @Rabios can implement the game later.

### CODE REVIEW

**Comment by ghost** [comment]
@felladrin Very thankful, Just tell what I need to do and all will be ready soon! 🚀

**Comment by felladrin** [comment]
@end3r, could you please add to Readme the basic functonatility the breakout games should include?

**Comment by end3r** [comment]
I will, and we'll open this repo to other game engines and libraries soon, but right now we're focusing on those three already present as we'll be having their authors giving intros during live online meetup on August 13th.

**Comment by felladrin** [comment]
@Rabios, I will close this PR and ping you again later when the repo gets open for new contributions!

**Pull request closed without merging**
